### ISSUE TITLE
parse not require data to be written to a file prior to reading

### ISSUE THREAD

**Issue by shofetim** [hrathod/ofx-clj#1]
I'm downloading OFX data from institutions, and it would be very handy if parse could handle being passed a string, or file, or filename... :smiley:

**Comment by hrathod** [comment]
Sorry, I did not see this issue until now.  I have created the 'allow-files' branch to start work on this issue.  The parse function should now accept anything that clojure.java.io/input-stream function accepts.

https://github.com/hrathod/ofx-clj/tree/allow-files

Please try it out and let me know if that works for you.  I will have to do further work to add in the parsing of the string.  Possibly create another function, because it is hard to differentiate between an OFX string and a string which contains a file name or a URL.

**Comment by hrathod** [comment]
Updated branch with a 'parse-string' function that should do what you need.

**Comment by hrathod** [comment]
Branch is merged.  Let me know if you have any issues with the parse-string function.
